name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_DIR: ${{ github.workspace }}/android-sdk

    steps:
      - name: Repository setup
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure build
        run: |
            echo "sdk.dir=$ANDROID_SDK_DIR" > local.properties
            echo "API_KEY=\"${{ secrets.API_KEY }}\"" >> local.properties
            chmod +x gradlew

      - name: Build and Test
        run: |
          ./gradlew build test
          ./gradlew assembleDebug

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/reports/tests/testDebugUnitTest/
          retention-days: 7

      - name: Clean up
        run: rm -f local.properties