name: Android CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ANDROID_SDK_DIR: ${{ github.workspace }}/android-sdk
  GRADLE_OPTS: -Dorg.gradle.daemon=false
jobs:
  android-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Configure environment
        run: |
          echo "sdk.dir=$ANDROID_SDK_DIR" > local.properties
          if [ -n "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY=${{ secrets.API_KEY }}" >> local.properties
          else
            echo "API_KEY=\"test_key\"" >> local.properties
          fi
          chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test --stacktrace --info

      - name: Build release APK and AAB after test
        run: |
          ./gradlew assembleRelease --stacktrace --info
          ./gradlew bundleRelease --stacktrace --info

      - name: Save test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/**/*
            app/build/outputs/androidTest-results/connected/*

      - name: Save build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            app/build/**/*.log
            app/build/tmp/**/*.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab